import { Container } from '@/components/ui/Container';
const categories=[
 {title:'Express Wash',note:'Fast maintenance care',rows:[['Exterior Wash','₹149','₹179','₹199'],['Wash + Vacuum','₹299','₹299','₹349'],['Premium Foam Wash','₹399','₹399','₹499']]},
 {title:'Interior Care',note:'Cabin cleaning and restoration',rows:[['Interior Deep Cleaning','₹1,299','₹1,499','₹1,799'],['Seat Shampooing','₹899','₹1,099','₹1,299'],['Roof Liner Cleaning','₹499+','₹499+','₹499+'],['Engine Bay Cleaning','₹699+','₹699+','₹699+']]},
 {title:'Detailing Packages',note:'Curated complete services',rows:[['Silver Refresh','₹999','₹1,199','₹1,399'],['Gold Detail','₹2,299','₹2,699','₹3,199'],['Platinum Detail','₹4,499','₹5,499','₹6,499']]},
 {title:'Ceramic & Correction',note:'Gloss, clarity and protection',rows:[['Paint Enhancement','₹1,999','₹2,499','₹3,499'],['Paint Correction','₹4,999','₹6,999','₹8,999'],['Ceramic Lite','₹6,999','₹8,999','₹10,999'],['Premium Ceramic','₹12,999','₹15,999','₹18,999']]}
];
export function PricingPage(){return <><section className="border-b border-white/10 py-20 md:py-28"><Container><p className="gold-label">Pricing</p><h1 className="display title-lg mt-10">Choose the right finish.</h1><p className="bodycopy mt-8">Pricing is organised by service category and vehicle type. Final recommendation depends on paint condition and interior usage.</p></Container></section><section className="py-10 md:py-20"><Container><div className="grid gap-5">{categories.map(cat=><section key={cat.title} className="premium-card overflow-hidden"><div className="border-b border-white/10 p-6 md:p-8"><p className="gold-label">{cat.note}</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-.05em] md:text-5xl">{cat.title}</h2></div><div className="grid divide-y divide-white/10">{cat.rows.map(row=><div key={row[0]} className="grid gap-5 p-6 md:grid-cols-[1.5fr_repeat(3,.75fr)] md:items-center md:p-7"><div className="font-display text-xl font-extrabold tracking-[-.035em] md:text-2xl">{row[0]}</div><div className="grid grid-cols-3 gap-2 md:contents"><Price label="Hatchback" value={row[1]}/><Price label="Sedan" value={row[2]}/><Price label="SUV" value={row[3]}/></div></div>)}</div></section>)}</div></Container></section></>}
function Price({label,value}:{label:string;value:string}){return <div className="rounded-sm border border-white/10 bg-white/[.025] p-3 md:border-0 md:bg-transparent md:p-0"><div className="text-[9px] font-black uppercase tracking-[.28em] text-white/35 md:hidden">{label}</div><div className="mt-1 font-display text-lg font-extrabold text-champagne md:mt-0 md:text-2xl">{value}</div></div>}
